### PR TITLE
Fix cursor display in ReadOnly mode.

### PR DESCRIPTION
**Pull request by audetto**
1) do not display cursor if outside displayed area (if can happen with scrolling)
2) index arithmetic was wrong
3) take into account _pxSelectionSub when filling the rectangle
4) draw ascii with the same logic at line 899-904

Now it works, but due to the fact that the cursor background is painted with viewport()->palette().color(QPalette::Base). The cursor is actually invisible. I tested this patch with a yellow background.

Signed-off-by: Andrea Odetti <mariofutire@gmail.com>

### CODE REVIEW

**Comment by audetto** [comment]
Fix an issue whereby the cursor in hex mode was always printing the left character of the 2 hex digits even when under the right one.

**Comment by Simsys** [comment]
Is this pull request still relevant?

**Comment by audetto** [comment]
Yes, but I still have a small tear which I think is due to the exact coordinates of the rectangles.
I would like to fix it completely.

**Comment by audetto** [comment]
I have removed the tear in the read only mode.

It is still present in read/write.
I explained in the commit message.

After calling 

viewport()->update(_cursorRect);

One must repaint _cursorRect completely otherwise is become white.
When the cursor is not blinking or we have no focus, the _cursorRect stays white.
Easy to view for a vertical cursor in overwrite mode.

But in read only this has gone and I have changed the background so one can see it.

**Comment by audetto** [comment]
This solves the problem with !readOnly.
The only think I can't figure out is why the character under the cursor is painted slightly darker.
I tried to find where this different color is set in the painter but I could not find out.

When the cursor is blink=false, one can see the underlying character rather than a block of white.

**Comment by Simsys** [comment]
fixed, see 3b9d90a

**Pull request closed without merging**
