### PR TITLE
Add colors customization

### PR DESCRIPTION
**Pull request by ktrace**
Add properties addressFontColor, asciiFontColor, hexFontColor, addressAreaColor (taken from lancos, needed for ponyprog), PR #82 reincarnation, but with correct asciiArea drawing.

### CODE REVIEW

**Comment by ktrace** [comment]
hmmm... and look like CI broken...

**Comment by Simsys** [comment]
These are a lot of changes that make sense but have nothing to do with each other:
- Extension of the Lib API by the properties asciiAreaColor, addressFontColor, asciiFontColor, hexFontColor (here the change of the Lib Versin in qhexedit.pro to 4.2.0 is missing and also qhexedit.sip was not adapted)
- Cleanup of Typos
- Changing the displayed characters in asciiAerea

Please divide into single consistent Pull Requests

Thank you very much

**Comment by ktrace** [comment]
rebase to current master, rearrange on two commits.

**Comment by Simsys** [comment]
Hi Viktor,

thanks for the patches and the effort you put into the QHexEdit project. Unfortunately I can't accept the pull request because something was destroyed with the cursor handling.

The normal behavior is:
- Read Only Mode: Curser does not blink, is transparent grey
- Normal fashion:
  - Insert: Vertical blinking cursor (line) to the left of the input character.
  - Overwrite: horizontal flashing cursor (line) below the input character

After your changes:
- Read Only Mode and Normal Mode: Cursor does not blink and is always transparent gray

Please correct, then I'll accept the patches.

**Comment by ktrace** [comment]
Fixed.

**Comment by Simsys** [comment]
The cursor does not blink, it appears continuously

**Comment by ktrace** [comment]
blink returns, please check it

**Comment by Simsys** [comment]
Hi Victor,

thanks for the patches and the effort you put into the QHexEdit project.

Unfortunately the patch still doesn't work for me. It is now again the case that the cursor is a gray area independent of the mode (insert, overwrite) that does not blink.

The normal behavior is:

Read Only Mode: 
- Curser does not blink, is transparent grey

Normal fashion:
- Insert: Vertical blinking cursor (line) to the left of the input character.
- Overwrite: horizontal flashing cursor (line) below the input character

Something seems to have gotten mixed up.

**Comment by ktrace** [comment]
Hi Simsys, look like it work now as wanted.

**Comment by Simsys** [comment]
I see nothing to merge. Please open a new Pull Request, if necessary

**Comment by bearsh** [comment]
@Simsys strange, I see 2 commits and 8 changed files, maybe github fooled you at that time you closed this...

**Comment by bearsh** [comment]
rebased to current master in #120

**Comment by Simsys** [comment]
closed, see #120

**Pull request closed without merging**
