### PR TITLE
Miscalculation of the position of cursor when we scroll horizontally

### PR DESCRIPTION
**Pull request by mad3l**
Take the horizontal scrolling into consideration when we draw the cursor or get its position.

### CODE REVIEW

**Comment by Simsys** [comment]
Thanks for reporting this.

I see the issue, but your soulution doessn't work for me. I open an issue instead

**Comment by mad3l** [comment]
Sorry i didn't clarify this before where i said 

> Take the horizontal scrolling into consideration when we **draw the cursor** or **get its position**. 

so let me point another issue that should be fixed
when you scroll horizontally the cursor position needs to be adjust too when we select or interact with the data, that's why i did lot of changes.

Thank you,

**Comment by Simsys** [comment]
The horizontal scrolling is now consodered, when we draw the cursor.

But you are right: When we get the position, the horizontal scrolling is not taken in consideration. I will open an issue for that.

**Comment by Simsys** [comment]
fixed, see
  - ffbcfef59dbd56f7d4415953c4d1d4da51d2b635
  - 19c7500c2cf13aa9b19b4ef986ee881928943654

**Pull request closed without merging**
