### PR TITLE
Add select highlight pattern

### PR DESCRIPTION
**Pull request by Logintar**
Highlighting occur of selected data in whole file

### CODE REVIEW

**Comment by Simsys** [comment]
Please describe exactly, why you want to change this. What are the benefits. This is a API breaking change and in case of acceptance, we have to change the major API version. So we need a good reason.

**Comment by Logintar** [comment]
I'm work a lot of time with hex files and in my opinion it is useful feature to highlight some repeating data by selecting it. Other hex editors also have that feature, eg. PowerGREP, Bless, HexEdit

**Comment by Simsys** [comment]
The idea is very cool. 

Unfortunately the realization is a bit buggy. I load qhexedit.o and select 00 00 00 01 then I got all the occurrences highlighted (pic 1). When I scroll down (mouse and right slider) and up, only the highlighting disappears (pic 2).

image

image

**Comment by Logintar** [comment]
I'll fix this bug.

**Comment by Simsys** [comment]
This pull request has a major change to the external API of QHexEdit. The API should only be changed if this is absolutely necessary, since the component is used by many projects. If we change the API, they'll have to change their code. There's gonna be trouble.

If changes are necessary, then only as much as is necessary.

**Pull request closed without merging**
